/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_system;

import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class feed_panel extends javax.swing.JPanel {

    FlowLayout Grid = new FlowLayout(FlowLayout.LEFT);

    GridBagConstraints gs = new GridBagConstraints();

    /**
     * Creates new form feed_panel
     */
    public feed_panel() {
        initComponents();
        jPanel1.setLayout(Grid);
        load_feedback();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(935, 491));
        setMinimumSize(new java.awt.Dimension(935, 491));
        setPreferredSize(new java.awt.Dimension(935, 491));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(437, 401));
        jPanel1.setMinimumSize(new java.awt.Dimension(437, 401));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(437, 401));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 450, -1));

        jLabel1.setBackground(new java.awt.Color(244, 108, 108));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEEDBACK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void load_feedback() {

        try {
            GridBagConstraints gs = new GridBagConstraints();
            set_con.setconnection();
            // set_con.setconnection();
            String q = "SELECT * FROM `order_` where feed_back IS NOT NULL";
            PreparedStatement statment = set_con.con.prepareStatement(q);
            ResultSet result = statment.executeQuery();

            while (result.next()) {                
                Feed_Item f_i = new Feed_Item(result.getInt("order_id"), result.getString("feed_back"));
                jPanel1.add(f_i, gs);
                f_i.setVisible(true);
            }
            set_con.con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Offers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
