/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_system;

import java.awt.GridBagConstraints;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import restaurant_system.item_;
import restaurant_system.set_con;

/**
 *
 * @author pc
 */
public class Inven_item extends javax.swing.JPanel {

    item_ item;
    String user_name = "ahmed";
    String pass = "111";
    String name = "ahmed mostafa";
    String phone = "128845";

    manager m = new manager(name, phone, user_name, pass);

    /**
     * Creates new form Inven_item
     */
    public Inven_item() {

    }

    // create new form inventory item

     public Inven_item(int id, String name, int quantity,int original_quantity, String photo, float price,float av_rate ,float discount, String message, String category_name , boolean check) {
        initComponents();
        //jButton2.setVisible(false);
        item =  new item_(id , name , quantity  ,original_quantity,photo , price, av_rate,discount , message , category_name, check);  
        item.LoadData(jLabel8, jLabel17, jLabel12, jLabel9, jLabel13, jLabel5, jLabel1,jCheckBox1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(760, 121));
        setMinimumSize(new java.awt.Dimension(760, 121));
        setPreferredSize(new java.awt.Dimension(760, 121));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_system/icons8_Food_100px.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 70));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel2.setText(" Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel3.setText(" Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 40, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel7.setText("Aavailable Qnt");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel10.setText(" Rate");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 40, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel11.setText(" Sold");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 40, 30));

        jButton1.setBackground(new java.awt.Color(15, 15, 15));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_system/icons8_delete_24px.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(null);
        jButton1.setIconTextGap(5);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 70, 30));

        jButton2.setBackground(new java.awt.Color(15, 15, 15));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_system/icons8_edit_file_24px.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorder(null);
        jButton2.setIconTextGap(5);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 50, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel8.setText("jLabel5");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel9.setText("jLabel5");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel12.setText("jLabel5");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 70, 30));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel13.setText("jLabel5");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel4.setText("Item ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, 30));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel17.setText("17");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBox1.setText("Add in main menu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        m.deleteitem(jLabel17);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /* Edit_Item edit = new Edit_Item(item);
         edit.setVisible(true);*/
        //System.exit(0);
        Edit_Item e = new Edit_Item(item);
        e.pack();
        e.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        try {
                  // TODO add your handling code here
                  m.update_checked_status(item, jCheckBox1);
              } catch (SQLException ex) {
                  Logger.getLogger(Inven_item.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
