package restaurant_system;

import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.sql.Date;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurant_system.Special_Offer;
import restaurant_system.Special_Offer;
import restaurant_system.set_con;
import restaurant_system.set_con;
import restaurant_system.set_con;


public class Offers_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Offers_Panel
     */
    FlowLayout Grid = new FlowLayout(FlowLayout.LEFT);

    GridBagConstraints gs = new GridBagConstraints();

    public Offers_Panel() {
        initComponents();

        jPanel1.setLayout(Grid);
        load_offers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(950, 491));
        setMinimumSize(new java.awt.Dimension(950, 491));
        setPreferredSize(new java.awt.Dimension(950, 491));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(828, 424));
        jPanel1.setMinimumSize(new java.awt.Dimension(828, 424));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 390, 380));

        jLabel9.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Offers ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void load_offers() {

        try {
            GridBagConstraints gs = new GridBagConstraints();
            set_con.setconnection();
            Special_Offer s_o = new Special_Offer();
            ArrayList<Item_Offer> item_arr = s_o.load_offers();
            item_arr.forEach(
                    promo -> {
                           promo.getItem_id();
                           load_data(promo.getMessage(),promo.getDisscount(),promo.getItem_id(),promo.getEnd_date());
                    }
            );

         
            set_con.con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Offers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

   

    private void load_data(String message, float disscount, int item_id, Date end_date) {
         String name="";
            String pic="";
    
     try {

            set_con.setconnection();
            String q = "select * from item where item_id="+item_id;
            PreparedStatement statment = set_con.con.prepareStatement(q);
            ResultSet result = statment.executeQuery();

            while (result.next()) {
             name=result.getString("name");
             pic=result.getString("photo");

            }
       Offers_Items o_i=new Offers_Items (message,name,pic,disscount,end_date);
                jPanel1.add(o_i, gs);

                o_i.setVisible(true);
            set_con.con.close();
            

        } catch (SQLException ex) {
            Logger.getLogger(Offers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
