/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_system;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NONA
 */
public class Order_Cart extends javax.swing.JPanel {

    int id, quantity;
    double price, total;
    String name;
    order ord;

    /**
     * Creates new form Order_Cart
     */
    public Order_Cart(int id, int quantity, double price, double total, String name, order ord) {
        initComponents();
        this.id = id;
        this.quantity = quantity;
        this.price = price;
        this.total = total;
        this.name = name;
        this.ord = ord;
        load_data();
    }

    /**
     * *
     * load data of item in his place
     */
    private void load_data() {
        jLabel1.setText(String.valueOf(quantity));
        jLabel3.setText(name);
        jLabel2.setText(String.valueOf(price));
        jLabel4.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(320, 40));
        setPreferredSize(new java.awt.Dimension(320, 40));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("QNT");
        jLabel1.setToolTipText("Quantity");
        add(jLabel1);
        jLabel1.setBounds(6, 11, 26, 14);

        jLabel2.setText("Price");
        jLabel2.setToolTipText("Price");
        add(jLabel2);
        jLabel2.setBounds(170, 10, 50, 14);

        jLabel3.setText("Item");
        jLabel3.setToolTipText("Item Name");
        add(jLabel3);
        jLabel3.setBounds(50, 10, 120, 14);

        jLabel4.setText("Total");
        jLabel4.setToolTipText("Total");
        add(jLabel4);
        jLabel4.setBounds(230, 10, 40, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_system/icons8_delete_16px.png"))); // NOI18N
        jLabel5.setToolTipText("Delete");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5);
        jLabel5.setBounds(290, 10, 14, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setBackground(Color.RED);
        jLabel5.setVisible(false);
        ord.delete_item_from_order(Integer.valueOf(ord.getId()), id, quantity);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
